# Generated by Django 4.2.6 on 2023-10-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderUpdate',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=2000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
